/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_task_JNIProject */

#ifndef _Included_com_task_JNIProject
#define _Included_com_task_JNIProject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_task_JNIProject
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_task_JNIProject_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_task_JNIProject
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_task_JNIProject_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_task_JNIProject
 * Method:    difference
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_task_JNIProject_difference
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_task_JNIProject
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_task_JNIProject_multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_task_JNIProject
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_task_JNIProject_divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
